### ISSUE TITLE
Trying to build in Linux system fail 

### ISSUE THREAD

**Issue by DraGiuS** [rforshaw/MalletEngine#1]
Hello,
here the output : FAILURE: Build failed with an exception.

* What went wrong:
Could not open terminal for stdout: could not get termcap entry

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by rforshaw** [comment]
This appears to be an issue with Gradle. Make sure you are running the latest version of Gradle and test with a smaller project to ensure your Gradle is working as intended.

This may provide you with more insight: https://bbs.archlinux.org/viewtopic.php?id=38807
